### ISSUE TITLE
API Docs appear to be empty

### ISSUE THREAD

**Issue by awayken** [coldbox-modules/cbox-storages#3]
I installed the stable version (1.2.0) of this module to my ColdBox project. The documentation said to browse the API Docs to learn more about how to use it. I browsed to http://[local domain]/modules/cbstorages/apidocs but all that rendered were empty frames with no actual content. I opened my console, and there were no JavaScript errors.

![image](https://cloud.githubusercontent.com/assets/156215/18316293/a996d3b4-74df-11e6-9e09-f8bb538e2f9f.png)

Is there somewhere else I can go to read API Docs or is there an easy fix for this? I'd love to use this module in my project.

**Comment by lmajano** [comment]
Can you create an issue for this please

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057




On Wed, Sep 7, 2016 at 9:45 AM -0500, "Miles Rausch" <notifications@github.com> wrote:












I installed the stable version (1.2.0) of this module to my ColdBox project. The documentation said to browse the API Docs to learn more about how to use it. I browsed to http://[local domain]/modules/cbstorages/apidocs but all that rendered were empty frames with no actual content. I opened my console, and there were no JavaScript errors.







Is there somewhere else I can go to read API Docs or is there an easy fix for this? I'd love to use this module in my project.

**Comment by awayken** [comment]
@lmajano I'm not sure what you mean.

According to the ForgeBox and Readme file for this project, GitHub is the place to raise an issue about the project. Do you want an issue created in a different place? Or another issue created here?

**Comment by lmajano** [comment]
Sorry I thought this was a direct email to me :)

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057




On Wed, Sep 7, 2016 at 11:09 AM -0500, "Miles Rausch" <notifications@github.com> wrote:












@lmajano I'm not sure what you mean.



According to the ForgeBox and Readme file for this project, GitHub is the place to raise an issue about the project. Do you want an issue created in a different place? Or another issue created here?

**Comment by lmajano** [comment]
This has been fixed and will be in the next release. You can find the api docs in our CI server
http://integration.stg.ortussolutions.com/artifacts/ortussolutions/coldbox-modules/cbstorages/1.3.0/
